name: graduation_thesis_front_end
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^5.0.0

  fpdart: ^1.1.1
  supabase_flutter: ^2.8.3
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3
  image_picker: ^1.1.2
  uuid: ^4.5.1
  intl: ^0.20.2
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  transparent_image: ^2.0.1
  go_router: ^14.8.0
  flex_color_scheme: ^8.0.2
  image_cropper: ^9.0.0
  mask_text_input_formatter: ^2.9.0
  lottie: ^3.0.0
  dotted_border: ^2.1.0
  http: ^1.3.0
  confetti: ^0.8.0
  glass: ^2.0.0+2
  flutter_staggered_grid_view: ^0.7.0
  exif: ^3.3.0
  extended_image: ^9.1.0
  provider: ^6.1.2
  audioplayers: ^6.2.0
  percent_indicator: ^4.2.4
  timeago: ^3.2.2
  chewie: 1.8.0
  video_player: ^2.8.6
  speech_to_text: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/album_cover/
    - assets/images/slide1.jpg
    - assets/images/slide2.jpg
    - assets/images/slide3.jpg
    - assets/images/slide4.jpg
    - assets/images/login_banner.jpg
    - assets/images/sign_up_banner.jpg
    - assets/images/discord.webp
    - assets/images/google.webp
    - assets/images/placeholder.jpg
    - assets/images/slide_style_1.jpg
    - assets/images/slide_style_2.png
    - assets/images/spring.JPG
    - assets/images/summer.JPG
    - assets/images/fall.JPG
    - assets/images/winter.JPG
    - assets/images/alter/spring.JPG
    - assets/images/alter/summer.JPG
    - assets/images/alter/fall.JPG
    - assets/images/alter/winter.JPG
    - assets/images/wrong.webp
    # lottie file
    - assets/lottie/activity.json
    - assets/lottie/album.json
    - assets/lottie/location.json
    - assets/lottie/person.json
    - assets/lottie/video.json
    - assets/lottie/touch_here.json
    - assets/lottie/congrat.json
    - assets/lottie/loading.json
    - assets/lottie/loading_2.json
    - assets/lottie/video_loading.json
    - assets/lottie/video_done.json
    - assets/lottie/video_fail.json
    - assets/lottie/voice.json

    # music directory
    - assets/music/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
